<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKpggfiu\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKpggfiu/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKpggfiu.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKpggfiu\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKpggfiu\appDevDebugProjectContainer([
    'container.build_hash' => 'Kpggfiu',
    'container.build_id' => '27d9815e',
    'container.build_time' => 1571590570,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKpggfiu');
